name: Client

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.13]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: secret value test
      run: |
          cd ./client
          node secret.js ${{ secrets.TEST }}

    - name: install & request
      run: |
        cd ./client
        npm install
        node app.js ${{ secrets.SERVER_IP }}
      env:
        CI: true
